# Generated by Django 6.0.1 on 2026-01-13 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='id',
        ),
        migrations.AddField(
            model_name='curso',
            name='curso_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='docente',
            name='docente_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estudiante_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='inscripcion_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='periodo',
            name='periodo_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(db_column='docente_id', on_delete=django.db.models.deletion.PROTECT, to='core.docente'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(db_column='periodo_id', on_delete=django.db.models.deletion.PROTECT, to='core.periodo'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, to='core.curso'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estudiante',
            field=models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, to='core.estudiante'),
        ),
    ]
